#!/usr/bin/env bash
set -euo pipefail

# One-shot Linux installer for a personal CLIProxyAPI + Codex subscription gateway.

SERVICE_NAME="${CPA_SERVICE_NAME:-ai-sub-gateway}"
SERVICE_USER="${CPA_SERVICE_USER:-cliproxyapi}"
CONF_DIR="${CPA_CONF_DIR:-/etc/ai-sub-gateway}"
DATA_DIR="${CPA_DATA_DIR:-/var/lib/ai-sub-gateway}"
BIN_PATH="${CPA_BIN_PATH:-/usr/local/bin/cliproxyapi}"
CONFIG_PATH="$CONF_DIR/config.yaml"
ENV_PATH="$CONF_DIR/gateway.env"
UNIT_PATH="/etc/systemd/system/${SERVICE_NAME}.service"
# Community GitHub proxy. Set CPA_GITHUB_MIRROR=direct to disable it.
CPA_GITHUB_MIRROR="${CPA_GITHUB_MIRROR:-https://ghfast.top}"
UPSTREAM_INSTALLER_URL="https://raw.githubusercontent.com/router-for-me/cliproxyapi-installer/refs/heads/master/cliproxyapi-installer"
if [[ "$CPA_GITHUB_MIRROR" == "direct" || -z "$CPA_GITHUB_MIRROR" ]]; then
  INSTALLER_URL="${CPA_INSTALLER_URL:-$UPSTREAM_INSTALLER_URL}"
else
  INSTALLER_URL="${CPA_INSTALLER_URL:-$CPA_GITHUB_MIRROR/$UPSTREAM_INSTALLER_URL}"
fi

die() { echo "error: $*" >&2; exit 1; }
need() { command -v "$1" >/dev/null 2>&1 || die "missing command: $1"; }

[[ "$(uname -s)" == "Linux" ]] || die "this installer only supports Linux"
[[ "$(id -u)" -eq 0 ]] || die "run as root, for example: sudo bash deploy/install.sh"
need curl
need systemctl

CPA_HOST="${CPA_HOST:-127.0.0.1}"
CPA_PORT="${CPA_PORT:-8317}"
CPA_PROXY_URL="${CPA_PROXY_URL:-}"
CPA_API_KEY="${CPA_API_KEY:-}"

if [[ -z "$CPA_API_KEY" ]]; then
  [[ -r /dev/urandom ]] || die "set CPA_API_KEY explicitly; /dev/urandom is unavailable"
  CPA_API_KEY="cpa_$(od -An -tx1 -N24 /dev/urandom | tr -d ' \n')"
fi

if ! id -u "$SERVICE_USER" >/dev/null 2>&1; then
  useradd --system --home-dir "$DATA_DIR" --create-home --shell /usr/sbin/nologin "$SERVICE_USER"
fi
install -d -m 0750 -o "$SERVICE_USER" -g "$SERVICE_USER" "$CONF_DIR" "$DATA_DIR" "$DATA_DIR/auth"

if [[ ! -x "$BIN_PATH" ]]; then
  tmp_installer="$(mktemp)"
  trap 'rm -f "$tmp_installer"' EXIT
  echo "Downloading the official CLIProxyAPI Linux installer..."
  curl -fsSL "$INSTALLER_URL" -o "$tmp_installer"
  bash "$tmp_installer"
  if [[ ! -x "$BIN_PATH" ]]; then
    found_bin="$(command -v cliproxyapi || true)"
    [[ -n "$found_bin" && -x "$found_bin" ]] || die "CLIProxyAPI was not found; set CPA_BIN_PATH and rerun"
    install -m 0755 "$found_bin" "$BIN_PATH"
  fi
fi

if [[ ! -f "$CONFIG_PATH" ]]; then
  cat > "$CONFIG_PATH" <<EOF
host: "$CPA_HOST"
port: $CPA_PORT
auth-dir: "$DATA_DIR/auth"
api-keys:
  - "$CPA_API_KEY"
proxy-url: "$CPA_PROXY_URL"
routing:
  strategy: "round-robin"
  session-affinity: false
codex:
  disable-codex-cloaking: false
EOF
else
  echo "Keeping existing config: $CONFIG_PATH"
fi

cat > "$ENV_PATH" <<EOF
# Generated by deploy/install.sh. Keep this file private.
CPA_BASE_URL=http://127.0.0.1:$CPA_PORT/v1
CPA_MODEL=gpt-5.6-luna
CPA_API_KEY=$CPA_API_KEY
EOF

chown "$SERVICE_USER:$SERVICE_USER" "$CONFIG_PATH" "$ENV_PATH"
chmod 0600 "$CONFIG_PATH" "$ENV_PATH"

cat > "$UNIT_PATH" <<EOF
[Unit]
Description=Personal Codex subscription gateway (CLIProxyAPI)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$SERVICE_USER
Group=$SERVICE_USER
ExecStart=$BIN_PATH -config $CONFIG_PATH
Restart=on-failure
RestartSec=3
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=$DATA_DIR
EnvironmentFile=-$ENV_PATH

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now "$SERVICE_NAME"

echo
echo "Installed and started: $SERVICE_NAME"
echo "Config: $CONFIG_PATH"
echo "Local API: http://127.0.0.1:$CPA_PORT/v1"
echo "Model: gpt-5.6-luna"
echo "API key: $CPA_API_KEY"
echo
echo "Next step (one-time OAuth login):"
echo "  sudo -u $SERVICE_USER $BIN_PATH -config $CONFIG_PATH -codex-login --no-browser"
